name: kepp_resources
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
